export const PLANET_DATA = {
  mercury: {
    name: "Mercury",
    size: 0.383,
    distance: 10,
    speed: 4.787,
    textureUrl: "/textures/mercury.jpg",
  },
  venus: {
    name: "Venus",
    size: 0.949,
    distance: 15,
    speed: 3.502,
    textureUrl: "/textures/venus.jpg",
  },
  earth: {
    name: "Earth",
    size: 1,
    distance: 20,
    speed: 2.978,
    textureUrl: "/textures/earth.jpg",
  },
  mars: {
    name: "Mars",
    size: 0.532,
    distance: 25,
    speed: 2.407,
    textureUrl: "/textures/mars.jpg",
  },
  jupiter: {
    name: "Jupiter",
    size: 11.209,
    distance: 35,
    speed: 1.307,
    textureUrl: "/textures/jupiter.jpg",
  },
  saturn: {
    name: "Saturn",
    size: 9.449,
    distance: 45,
    speed: 0.969,
    textureUrl: "/textures/saturn.jpg",
    rings: {
      innerRadius: 10,
      outerRadius: 20,
      textureUrl: "/textures/saturn-rings.jpg",
    },
  },
  uranus: {
    name: "Uranus",
    size: 4.007,
    distance: 55,
    speed: 0.681,
    textureUrl: "/textures/uranus.jpg",
  },
  neptune: {
    name: "Neptune",
    size: 3.883,
    distance: 65,
    speed: 0.543,
    textureUrl: "/textures/neptune.jpg",
  },
};
